apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-slave-1
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-slave-1
    spec:
      containers:
      - name: jenkins-slave-1
        image: jenkinsci/jnlp-slave:2.60
        args:
          - "-url"
          - "http://$(JENKINS_DISCOVERY_SERVICE_HOST):$(JENKINS_UI_INTERNAL_SERVICE_PORT)"
          - "$(JENKINS_SECRET)"
          - "$(JENKINS_AGENT_NAME)"
        env:
          - name: JENKINS_SECRET
            value: f447cf73c6f5ef74b0d7745590d82893d5a86132b6977d184ae2a457183a9b02
          - name: JENKINS_AGENT_NAME
            value: slave-1
