apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
